@startuml
skinparam classAttributeIconSize 0
!include ../Memento.puml
!include ../Energia.puml
remove EstadoEnergia
remove Energizado
remove NoEnergizado
class PuertoEstelar {
+ <<Create>> PuertoEstelar(Area,Protoss,ArrayList<Estructura>)
+ MementoOperativo guardarEstado()
+ void restaurarEstado(MementoOperativo)
+ void actualizarEstado()
+ boolean permitirCorrelatividad(ConstruibleEstructura)
}
remove MementoOperativo
remove MementoInvisibilidad
remove UsaMementoInvisibilidad


UsaMementoOperativo <|.. PuertoEstelar
PuertoEstelar *-left- Energia
@enduml