@startuml
'https://plantuml.com/sequence-diagram
actor Usuario
participant "una:Unidad" as A
participant "comando:Atacar" as F
participant "__:EstadoOperativo__" as G
participant "__:Ataque__" as C
participant "otra:Unidad" as B
participant "comando:RecibirAtaqueUnidad" as H
participant "__:EstadoInvisibilidad__" as I
participant "__:EstadoOperativo__" as J
participant "__:Escudo__" as D
participant "__:Vida__" as E


Usuario -> A : atacar(otra)
create F
A -> F : <<create>>
A ->G : operable(comando)
G->F :ejecutar()
F -> C : atacar(otra, areaAtacante, razaAtacante)
C -> B : recibirAtaque(this, una)
B -> C : calcularDanio(this.tipoUnidad)
return danioARecibir
create H
B -> H:<<create>>
B -> I : atacable(comando)
return comando
B-> J : operable(comando)
J -> H: ejecutar()
H -> B : daniar(danioARecibir, una)
B -> D : proteger(danioARecibir, una)
D -> E : daniar(danioARecibir, una)
note right E: La vida llega a 0
E -> B : destruir()
E -> A : sumarBaja()

@enduml