@startuml
skinparam classAttributeIconSize 0
!include ../ExtraeRecurso.puml
class Zangano {
- Zerg zerg
+ <<Create>> Zangano(Area,ArrayList<Estructura>,Zerg)
+ void moverse(Area)
+ void usarExtractor(Area)
+ void extraerRecurso()
+ void pasarTurno()
+ boolean movible(Recurso)
}


ExtraeRecurso <|.. Zangano

@enduml