@startuml
skinparam classAttributeIconSize 0
class Coordenada {
- int posicionX
- int posicionY
+ <<Create>> Coordenada(int,int)
+ boolean enRango(Coordenada,int)
+ boolean esOpuesta(Coordenada)
+ boolean es(Coordenada)
}
@enduml